"""Contract Tests for OpenAPI Schema

Validates the OpenAPI schema generated by FastAPI for completeness and correctness.
"""

import pytest
from fastapi.testclient import TestClient
from src.main import app


class TestOpenAPISchema:
    """Test OpenAPI schema validation."""

    def test_openapi_schema_is_accessible(self):
        """Test that OpenAPI schema endpoint is accessible."""
        client = TestClient(app)
        response = client.get("/openapi.json")

        assert response.status_code == 200
        schema = response.json()
        assert "openapi" in schema
        assert schema["openapi"].startswith("3.")

    def test_openapi_info_metadata(self):
        """Test OpenAPI info section has correct metadata."""
        client = TestClient(app)
        response = client.get("/openapi.json")
        schema = response.json()

        assert "info" in schema
        assert schema["info"]["title"] == "Todo API - Phase 2"
        assert "version" in schema["info"]
        assert "description" in schema["info"]

    def test_task_create_endpoint_defined(self):
        """Test POST /api/{user_id}/tasks endpoint is defined."""
        client = TestClient(app)
        response = client.get("/openapi.json")
        schema = response.json()

        assert "/api/{user_id}/tasks" in schema["paths"]
        assert "post" in schema["paths"]["/api/{user_id}/tasks"]

        create_endpoint = schema["paths"]["/api/{user_id}/tasks"]["post"]
        assert create_endpoint["operationId"] == "create_task_api__user_id__tasks_post"
        assert "201" in create_endpoint["responses"]

    def test_task_list_endpoint_has_query_params(self):
        """Test GET /api/{user_id}/tasks has all query parameters."""
        client = TestClient(app)
        response = client.get("/openapi.json")
        schema = response.json()

        list_endpoint = schema["paths"]["/api/{user_id}/tasks"]["get"]
        parameters = list_endpoint["parameters"]
        param_names = [p["name"] for p in parameters]

        # Check for advanced query parameters
        assert "completed" in param_names
        assert "search" in param_names
        assert "priority" in param_names
        assert "tags" in param_names
        assert "sort_by" in param_names
        assert "sort_direction" in param_names
        assert "limit" in param_names
        assert "offset" in param_names

    def test_priority_type_enum_in_schema(self):
        """Test PriorityType enum is defined in components."""
        client = TestClient(app)
        response = client.get("/openapi.json")
        schema = response.json()

        # Priority enum should be in TaskCreate or TaskResponse schema
        assert "components" in schema
        assert "schemas" in schema["components"]

        # Check TaskCreate has priority field
        task_create = schema["components"]["schemas"]["TaskCreate"]
        assert "priority" in task_create["properties"]

        # Priority should have enum values
        priority_field = task_create["properties"]["priority"]
        if "$ref" in priority_field:
            # Follow the reference
            ref = priority_field["$ref"].split("/")[-1]
            assert ref in schema["components"]["schemas"]
            priority_enum = schema["components"]["schemas"][ref]
            assert "enum" in priority_enum
            assert set(priority_enum["enum"]) == {"High", "Medium", "Low"}
        else:
            # Inline enum
            assert "enum" in priority_field or "anyOf" in priority_field

    def test_task_response_schema_has_all_fields(self):
        """Test TaskResponse schema includes all fields."""
        client = TestClient(app)
        response = client.get("/openapi.json")
        schema = response.json()

        task_response = schema["components"]["schemas"]["TaskResponse"]
        properties = task_response["properties"]

        # Check all required fields
        assert "id" in properties
        assert "user_id" in properties
        assert "title" in properties
        assert "description" in properties
        assert "completed" in properties
        assert "priority" in properties
        assert "due_date" in properties
        assert "tags" in properties
        assert "created_at" in properties
        assert "updated_at" in properties

    def test_tag_with_usage_schema_defined(self):
        """Test TagWithUsage schema is defined."""
        client = TestClient(app)
        response = client.get("/openapi.json")
        schema = response.json()

        assert "TagWithUsage" in schema["components"]["schemas"]
        tag_schema = schema["components"]["schemas"]["TagWithUsage"]

        assert "name" in tag_schema["properties"]
        assert "usage_count" in tag_schema["properties"]

    def test_tags_endpoint_defined(self):
        """Test GET /api/{user_id}/tags endpoint is defined."""
        client = TestClient(app)
        response = client.get("/openapi.json")
        schema = response.json()

        assert "/api/{user_id}/tags" in schema["paths"]
        assert "get" in schema["paths"]["/api/{user_id}/tags"]

        tags_endpoint = schema["paths"]["/api/{user_id}/tags"]["get"]
        assert "200" in tags_endpoint["responses"]

        # Response should be array of TagWithUsage
        response_schema = tags_endpoint["responses"]["200"]["content"]["application/json"]["schema"]
        assert "type" in response_schema and response_schema["type"] == "array"

    def test_update_task_endpoint_defined(self):
        """Test PUT /api/{user_id}/tasks/{task_id} endpoint is defined."""
        client = TestClient(app)
        response = client.get("/openapi.json")
        schema = response.json()

        assert "/api/{user_id}/tasks/{task_id}" in schema["paths"]
        assert "put" in schema["paths"]["/api/{user_id}/tasks/{task_id}"]

        update_endpoint = schema["paths"]["/api/{user_id}/tasks/{task_id}"]["put"]
        assert "200" in update_endpoint["responses"]

    def test_delete_task_endpoint_defined(self):
        """Test DELETE /api/{user_id}/tasks/{task_id} endpoint is defined."""
        client = TestClient(app)
        response = client.get("/openapi.json")
        schema = response.json()

        assert "delete" in schema["paths"]["/api/{user_id}/tasks/{task_id}"]
        delete_endpoint = schema["paths"]["/api/{user_id}/tasks/{task_id}"]["delete"]

        # Delete should return 204 No Content
        assert "204" in delete_endpoint["responses"]

    def test_toggle_completion_endpoint_defined(self):
        """Test PATCH /api/{user_id}/tasks/{task_id}/complete endpoint is defined."""
        client = TestClient(app)
        response = client.get("/openapi.json")
        schema = response.json()

        assert "/api/{user_id}/tasks/{task_id}/complete" in schema["paths"]
        assert "patch" in schema["paths"]["/api/{user_id}/tasks/{task_id}/complete"]

        toggle_endpoint = schema["paths"]["/api/{user_id}/tasks/{task_id}/complete"]["patch"]
        assert "200" in toggle_endpoint["responses"]

    def test_all_endpoints_require_authentication(self):
        """Test all endpoints require Bearer authentication."""
        client = TestClient(app)
        response = client.get("/openapi.json")
        schema = response.json()

        # Check security scheme is defined
        assert "components" in schema
        assert "securitySchemes" in schema["components"]
        assert "BearerAuth" in schema["components"]["securitySchemes"]

        # Verify it's HTTP bearer
        bearer_scheme = schema["components"]["securitySchemes"]["BearerAuth"]
        assert bearer_scheme["type"] == "http"
        assert bearer_scheme["scheme"] == "bearer"

    def test_validation_error_schema_defined(self):
        """Test HTTP validation error schema is defined."""
        client = TestClient(app)
        response = client.get("/openapi.json")
        schema = response.json()

        # FastAPI includes HTTPValidationError by default
        assert "HTTPValidationError" in schema["components"]["schemas"]

    def test_task_create_schema_validation(self):
        """Test TaskCreate schema has proper validation."""
        client = TestClient(app)
        response = client.get("/openapi.json")
        schema = response.json()

        task_create = schema["components"]["schemas"]["TaskCreate"]

        # Title should be required
        assert "required" in task_create
        assert "title" in task_create["required"]

        # Title should have max length
        title_field = task_create["properties"]["title"]
        assert "maxLength" in title_field
        assert title_field["maxLength"] == 200

    def test_task_update_schema_allows_partial_updates(self):
        """Test TaskUpdate schema allows partial updates (all fields optional)."""
        client = TestClient(app)
        response = client.get("/openapi.json")
        schema = response.json()

        task_update = schema["components"]["schemas"]["TaskUpdate"]

        # TaskUpdate should have no required fields (all optional for partial updates)
        if "required" in task_update:
            assert len(task_update["required"]) == 0
